---
# Handlers for common role

- name: restart sshd
  service:
    name: "{{ _common_ssh_service_name[ansible_os_family] | default('sshd') }}"
    state: restarted

- name: restart fail2ban
  service:
    name: fail2ban
    state: restarted

- name: reload sysctl
  command: sysctl -p

- name: restart ntp
  service:
    name: "{{ _common_ntp_service_name[ansible_os_family] | default('ntp') }}"
    state: restarted
