apiVersion: v1
kind: ServiceAccount
metadata:
  name: compliance-scanner
  namespace: compliance
  annotations:
    # IRSA: grant pod access to DynamoDB and Lambda via IAM Role for Service Accounts
    eks.amazonaws.com/role-arn: "arn:aws:iam::123456789012:role/compliance-scanner-irsa-role"
  labels:
    app: compliance-scanner
automountServiceAccountToken: true
